In [2]:
import numpy as np

np arrays are fixed sized in themselves

In [ ]:
list1 = [1,2,3,4,5]
arr = np.array(list1)

In [ ]:
arr.shape

(5,)

In [ ]:
for i in arr:
  print(i)

1
2
3
4
5


instead of extending the list, broadcasted addition will be done,
the elems will be multiplied

In [ ]:
list2 = [6,7,8,9,10]
arr2 = np.array(list2)
arr3 = arr + arr2


In [ ]:
print(arr3)

[ 7  9 11 13 15]


In [ ]:
print(arr3 * 2)

[14 18 22 26 30]


In [ ]:
print(list2 * 2)

[6, 7, 8, 9, 10, 6, 7, 8, 9, 10]


#**Dot Product**

In [ ]:
a = np.array([2,4])
b = np.array([8,6])
c = np.dot(a,b)

In [ ]:
c

40

In [ ]:
c = np.sum(a*b)

In [ ]:
print(c)

40


In [ ]:
a_magnitude = np.sqrt((a*a).sum())
print(a_magnitude)

4.47213595499958


In [ ]:
np.linalg.norm(a)

4.47213595499958

In [ ]:
cosangle = a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
print("The angle between two vectors is : ",cosangle)

The angle between two vectors is :  0.8944271909999159


# **MATMUL**

In [ ]:
mat_a = np.array([[1,2],[3,4]])
mat_b = np.array([[5,6],[7,8]])
mat_a_det = np.linalg.det(mat_a)
mat_b_det = np.linalg.det(mat_b)

In [ ]:
mat_a_det

-2.0000000000000004

In [ ]:
mat_a.dot(mat_b)

array([[19, 22],
       [43, 50]])

In [ ]:
np.matmul(mat_a,mat_b)

array([[19, 22],
       [43, 50]])

In [ ]:
#eigen values, eigen vectors
lam,v = np.linalg.eig(mat_a)

In [ ]:
v[:,0] * lam[0] == mat_a @ v[:,0]

array([ True, False])

#**Solving eqns**

In [ ]:
eq1 = np.array([[1,1],[1.5,4]])
eq2 = np.array([2200,5050])

In [ ]:
np.linalg.solve(eq1,eq2)

array([1500.,  700.])

# **Generating Data**

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
10*np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.random.random((2,3))

array([[0.82409059, 0.17982482, 0.59479587],
       [0.46887124, 0.72873252, 0.26295557]])

In [7]:
np.random.randn(2,3)
#mean 1 and variance 0

array([[ 1.1651123 ,  0.583854  , -0.96463723],
       [-0.60155719,  0.50276724,  2.46431186]])

In [8]:
random_matrix = np.random.randn(2,3)
print(random_matrix.mean())
print(random_matrix.var())

0.29352526413670216
0.711531820099497


In [9]:
np.mean(random_matrix)

0.29352526413670216

In [10]:
np.var(random_matrix)

0.711531820099497

In [11]:
R = np.random.randn(10000,3)

In [13]:
#mean of each row
R.mean(axis = 0)

array([-0.01202339,  0.00589607,  0.00226612])

In [16]:
R.mean(axis = 1).shape

(10000,)

# **SpeedTest Matrix Multiplication**

In [17]:
import time

In [ ]:
mat1 = [[1,2,3],
        [4,5,6],
        [7,8,9]]
mat2 = [[2,4,0],
        [1,4,6],
        [10,8,7]]
